[workspace]
authors = ["Maxime RIO <maxime.rio@niwa.co.nz>"]
channels = ["conda-forge"]
name = "tinypet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.7,<5"
python = ">=3.13.7,<3.14"
xarray = ">=2025.9.0,<2026"
zarr = ">=3.1.2,<4"
dask = ">=2025.7.0,<2026"
